#!/bin/bash

WORKING_DIRECTORY=./build/bake
BAKE_BOOTSTRAP_DIRECTORY=$WORKING_DIRECTORY/cli
BAKE_BOOTSTRAP_CLI=$BAKE_BOOTSTRAP_DIRECTORY/BakeCLI
BAKE_CLI=$WORKING_DIRECTORY/bootstrap/bake
BRANCH=main

run_silent() {
    local output
    output=$("$@" 2>&1)
    local status=$?

    if [ $status -ne 0 ]; then
        echo "Command failed: $*"
        echo "$output"
        return $status
    fi
    return 0
}

progress() {
	stop_spinner
  start_spinner "$1" &
  SPINNER_PID=$!
}

start_spinner() {
    local text="$1"
    local spin='⠋⠙⠹⠸⠼⠴⠦⠧⠇⠏'
    local i=0

    while true; do
        i=$(( (i+1) % 10 ))
        printf "\r${spin:$i:1} $text"
        sleep 0.1
    done
}

stop_spinner() {
    kill $SPINNER_PID 2>/dev/null
    wait $SPINNER_PID 2>/dev/null
    printf "\r\033[K"  # Clear the spinner line
}


bootstrap() {
	progress "Bootstrap"
	if [ -d "$WORKING_DIRECTORY" ]; then
		rm -rf "$WORKING_DIRECTORY"
	fi

	mkdir -p $BAKE_BOOTSTRAP_DIRECTORY
	SOURCE_DIRECTORY=$BAKE_BOOTSTRAP_DIRECTORY/checkout
	progress "Clone"
	git clone --quiet -b $BRANCH https://github.com/openbakery/bake.git $SOURCE_DIRECTORY

	progress "Build"
	run_silent swift build --quiet -c release --package-path $SOURCE_DIRECTORY

	mv $SOURCE_DIRECTORY/.build/arm64-apple-macosx/release/BakeCLI $BAKE_BOOTSTRAP_CLI

	progress "Bootstrap"
	$BAKE_BOOTSTRAP_CLI bootstrap > /dev/null
}

parameters=()

for parameter in "$@"; do
    if [ "$parameter" != "--refresh" ]; then
        parameters+=("$parameter")
		else
		rm -rf "$WORKING_DIRECTORY"
    fi
done

trap stop_spinner EXIT
start_spinner "Initializing build..." &
SPINNER_PID=$!

if [ ! -f "$BAKE_CLI" ]; then
	bootstrap
elif [ ! -f "$BAKE_BOOTSTRAP_CLI" ]; then
	bootstrap
fi


$BAKE_CLI "${parameters[@]}"


